feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000
        errorDecoder: com.springboot.netflix.oss.feign.exceptionhandler.CustomExceptionHandler

  hystrix:
    enabled: true